FROM ubuntu:22.04

ENV PYTHONUNBUFFERED=1
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install git neovim nodejs npm golang python3 python3-pip wget curl unzip -y
RUN ln -sf /usr/bin/python3 /usr/bin/python

